[package]
name = "tikibase"
version = "0.0.0"
authors = ["Kevin Goslar <kevin.goslar@gmail.com>"]
edition = "2018"

[dependencies]

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest

[dev-dependencies]
cucumber = { package = "cucumber_rust", version = "0.8.3" }
# You can use any executor you want, but we're going to use Tokio in this example.
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
