[package]
name = "tikibase"
version = "0.3.0"
authors = ["Kevin Goslar <kevin.goslar@gmail.com>"]
edition = "2018"

[dependencies]
ahash = "0.7.4"
heck = "0.3.3"
once_cell = "1.9.0"
rand = "0.8.4"
regex = "1.5.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
walkdir = "2.3.2"

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest
test = false

[dev-dependencies]
cucumber_rust = { git = "https://github.com/bbqsrc/cucumber-rust", branch = "main" }
# You can use any executor you want, but we're going to use Tokio in this example.
tokio = { version = "1.10.1", features = ["macros", "rt-multi-thread"] }

[profile.release]
strip = "symbols"
lto = true
panic = 'abort'
