[package]
name = "tikibase"
version = "0.3.0"
authors = ["Kevin Goslar <kevin.goslar@gmail.com>"]
edition = "2021"
rust-version = "1.59"

[dependencies]
ahash = "0.7.6"
clap = { version = "3.1.6", features = ["derive"] }
heck = "0.4.0"
once_cell = "1.9.0"
rand = "0.8.4"
regex = "1.5.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
walkdir = "2.3.2"

[[test]]
name = "cucumber"
harness = false # Allows Cucumber to print output instead of libtest
test = false

[dev-dependencies]
async-trait = "0.1.52"
cucumber = "0.12.0"
futures = "0.3.21"
indoc = "1.0.4"
pretty = { package = "pretty_assertions", version = "1.2.0" }

[profile.release]
strip = "symbols"
lto = true
panic = 'abort'
