name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    rust: nightly

    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy
      - name: Unit tests
        run: cargo test
      - name: Cucumber
        run: make cuke
