name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - id: cache-rust
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-rust-${{ hashFiles('Cargo.lock') }}
      - uses: dprint/check@v1.5
      - run: make setup-ci
      - run: make unit
      - run: make cuke
      - run: make lint
