name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          # override: true
          # components: rustfmt, clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0
      - name: Unit tests
        run: cargo test
      - name: Cucumber
        run: make cuke
