name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-02-13
          profile: minimal
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1.2.0
      - uses: dprint/check@v1.5
      - run: make setup
      - run: make unit
      - run: make cuke
      - run: make lint
